openapi: 3.0.3
info:
  title: Doc Hub API
  version: 1.0.0
  description: Документация АПИ 
servers:
  - url: /
paths:
  /hello:
    get:
      summary: Проверка работы
      tags: [System]
      responses:
        '200':
          description: Работает)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
  /documents:
    get:
      summary: Все документы
      tags: [Documents]
      responses:
        '200':
          description: Document list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DocumentResponse'
    post:
      summary: Загрузка документа
      tags: [Documents]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              required: [file]
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Докумен загружен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
        '400':
          description: Не правильный файл
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /documents/{id}:
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: integer
          format: int64
    get:
      summary: Получить документ по ID
      tags: [Documents]
      responses:
        '200':
          description: Document details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
        '404':
          description: Документа не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      summary: Переименовать документ
      tags: [Documents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateDocumentRequest'
      responses:
        '200':
          description: Документ обновлен
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DocumentResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Документа не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      summary: Удаление документа
      tags: [Documents]
      responses:
        '200':
          description: Документ удален
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '404':
          description: Документа не существует
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    MessageResponse:
      type: object
      properties:
        message:
          type: string
      required: [message]
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      required: [message]
    UpdateDocumentRequest:
      type: object
      properties:
        fileName:
          type: string
      required: [fileName]
    DocumentResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fileName:
          type: string
        storedFileName:
          type: string
        contentType:
          type: string
        size:
          type: integer
          format: int64
        storagePath:
          type: string
        status:
          type: string
          example: uploaded
        message:
          type: string
        uploadedAt:
          type: string
          format: date-time
      required:
        - id
        - fileName
        - storedFileName
        - contentType
        - size
        - storagePath
        - status
        - message
        - uploadedAt
